insert into countries(code, description, category) values('ALB','Albania','UM');
insert into countries(code, description, category) values('DZA','Algeria','UM');
insert into countries(code, description, category) values('ASM','American Samoa','UM');
insert into countries(code, description, category) values('AND','Andorra','H');
insert into countries(code, description, category) values('AGO','Angola','LM');
insert into countries(code, description, category) values('ATG','Antigua and Barbuda','H');
insert into countries(code, description, category) values('ARG','Argentina','UM');
insert into countries(code, description, category) values('ARM','Armenia','UM');
insert into countries(code, description, category) values('ABW','Aruba','H');
insert into countries(code, description, category) values('AUS','Australia','H');
insert into countries(code, description, category) values('AUT','Austria','H');
insert into countries(code, description, category) values('AZE','Azerbaijan','UM');
insert into countries(code, description, category) values('BHS','Bahamas, The','H');
insert into countries(code, description, category) values('BHR','Bahrain','H');
insert into countries(code, description, category) values('BGD','Bangladesh','LM');
insert into countries(code, description, category) values('BRB','Barbados','H');
insert into countries(code, description, category) values('BLR','Belarus','UM');
insert into countries(code, description, category) values('BEL','Belgium','H');
insert into countries(code, description, category) values('BLZ','Belize','UM');
insert into countries(code, description, category) values('BEN','Benin','L');
insert into countries(code, description, category) values('BMU','Bermuda','H');
insert into countries(code, description, category) values('BTN','Bhutan','LM');
insert into countries(code, description, category) values('BOL','Bolivia','LM');
insert into countries(code, description, category) values('BIH','Bosnia and Herzegovina','UM');
insert into countries(code, description, category) values('BWA','Botswana','UM');
insert into countries(code, description, category) values('BRA','Brazil','UM');
insert into countries(code, description, category) values('VGB','British Virgin Islands','H');
insert into countries(code, description, category) values('BRN','Brunei Darussalam','H');
insert into countries(code, description, category) values('BGR','Bulgaria','UM');
insert into countries(code, description, category) values('BFA','Burkina Faso','L');
insert into countries(code, description, category) values('BDI','Burundi','L');
insert into countries(code, description, category) values('CPV','Cabo Verde','LM');
insert into countries(code, description, category) values('KHM','Cambodia','LM');
insert into countries(code, description, category) values('CMR','Cameroon','LM');
insert into countries(code, description, category) values('CAN','Canada','H');
insert into countries(code, description, category) values('CYM','Cayman Islands','H');
insert into countries(code, description, category) values('CAF','Central African Republic','L');
insert into countries(code, description, category) values('TCD','Chad','L');
insert into countries(code, description, category) values('CHI','Channel Islands','H');
insert into countries(code, description, category) values('CHL','Chile','H');
insert into countries(code, description, category) values('CHN','China','UM');
insert into countries(code, description, category) values('COL','Colombia','UM');
insert into countries(code, description, category) values('COM','Comoros','LM');
insert into countries(code, description, category) values('COD','Congo, Dem. Rep.','L');
insert into countries(code, description, category) values('COG','Congo, Rep.','LM');
insert into countries(code, description, category) values('CRI','Costa Rica','UM');
insert into countries(code, description, category) values('CIV','Côte dIvoire','LM');
insert into countries(code, description, category) values('HRV','Croatia','H');
insert into countries(code, description, category) values('CUB','Cuba','UM');
insert into countries(code, description, category) values('CUW','Curaçao','H');
insert into countries(code, description, category) values('CYP','Cyprus','H');
insert into countries(code, description, category) values('CZE','Czech Republic','H');
insert into countries(code, description, category) values('DNK','Denmark','H');
insert into countries(code, description, category) values('DJI','Djibouti','LM');
insert into countries(code, description, category) values('DMA','Dominica','UM');
insert into countries(code, description, category) values('DOM','Dominican Republic','UM');
insert into countries(code, description, category) values('ECU','Ecuador','UM');
insert into countries(code, description, category) values('EGY','Egypt, Arab Rep.','LM');
insert into countries(code, description, category) values('SLV','El Salvador','LM');
insert into countries(code, description, category) values('GNQ','Equatorial Guinea','UM');
insert into countries(code, description, category) values('ERI','Eritrea','L');
insert into countries(code, description, category) values('EST','Estonia','H');
insert into countries(code, description, category) values('SWZ','Eswatini','LM');
insert into countries(code, description, category) values('ETH','Ethiopia','L');
insert into countries(code, description, category) values('FRO','Faeroe Islands','H');
insert into countries(code, description, category) values('FJI','Fiji','UM');
insert into countries(code, description, category) values('FIN','Finland','H');
insert into countries(code, description, category) values('FRA','France','H');
insert into countries(code, description, category) values('PYF','French Polynesia','H');
insert into countries(code, description, category) values('GAB','Gabon','UM');
insert into countries(code, description, category) values('GMB','Gambia, The','L');
insert into countries(code, description, category) values('GEO','Georgia','UM');
insert into countries(code, description, category) values('DEU','Germany','H');
insert into countries(code, description, category) values('GHA','Ghana','LM');
insert into countries(code, description, category) values('GIB','Gibraltar','H');
insert into countries(code, description, category) values('GRC','Greece','H');
insert into countries(code, description, category) values('GRL','Greenland','H');
insert into countries(code, description, category) values('GRD','Grenada','UM');
insert into countries(code, description, category) values('GUM','Guam','H');
insert into countries(code, description, category) values('GTM','Guatemala','UM');
insert into countries(code, description, category) values('GIN','Guinea','L');
insert into countries(code, description, category) values('GNB','Guinea-Bissau','L');
insert into countries(code, description, category) values('GUY','Guyana','UM');
insert into countries(code, description, category) values('HTI','Haiti','L');
insert into countries(code, description, category) values('HND','Honduras','LM');
insert into countries(code, description, category) values('HKG','Hong Kong SAR, China','H');
insert into countries(code, description, category) values('HUN','Hungary','H');
insert into countries(code, description, category) values('ISL','Iceland','H');
insert into countries(code, description, category) values('IND','India','LM');
insert into countries(code, description, category) values('IDN','Indonesia','LM');
insert into countries(code, description, category) values('IRN','Iran, Islamic Rep.','UM');
insert into countries(code, description, category) values('IRQ','Iraq','UM');
insert into countries(code, description, category) values('IRL','Ireland','H');
insert into countries(code, description, category) values('IMN','Isle of Man','H');
insert into countries(code, description, category) values('ISR','Israel','H');
insert into countries(code, description, category) values('ITA','Italy','H');
insert into countries(code, description, category) values('JAM','Jamaica','UM');
insert into countries(code, description, category) values('JPN','Japan','H');
insert into countries(code, description, category) values('JOR','Jordan','UM');
insert into countries(code, description, category) values('KAZ','Kazakhstan','UM');
insert into countries(code, description, category) values('KEN','Kenya','LM');
insert into countries(code, description, category) values('KIR','Kiribati','LM');
insert into countries(code, description, category) values('PRK','Korea, Dem. Rep.','L');
insert into countries(code, description, category) values('KOR','Korea, Rep.','H');
insert into countries(code, description, category) values('XKX','Kosovo','UM');
insert into countries(code, description, category) values('KWT','Kuwait','H');
insert into countries(code, description, category) values('KGZ','Kyrgyz Republic','LM');
insert into countries(code, description, category) values('LAO','Lao PDR','LM');
insert into countries(code, description, category) values('LVA','Latvia','H');
insert into countries(code, description, category) values('LBN','Lebanon','UM');
insert into countries(code, description, category) values('LSO','Lesotho','LM');
insert into countries(code, description, category) values('LBR','Liberia','L');
insert into countries(code, description, category) values('LBY','Libya','UM');
insert into countries(code, description, category) values('LIE','Liechtenstein','H');
insert into countries(code, description, category) values('LTU','Lithuania','H');
insert into countries(code, description, category) values('LUX','Luxembourg','H');
insert into countries(code, description, category) values('MAC','Macao SAR, China','H');
insert into countries(code, description, category) values('MDG','Madagascar','L');
insert into countries(code, description, category) values('MWI','Malawi','L');
insert into countries(code, description, category) values('MYS','Malaysia','UM');
insert into countries(code, description, category) values('MDV','Maldives','UM');
insert into countries(code, description, category) values('MLI','Mali','L');
insert into countries(code, description, category) values('MLT','Malta','H');
insert into countries(code, description, category) values('MHL','Marshall Islands','UM');
insert into countries(code, description, category) values('MRT','Mauritania','LM');
insert into countries(code, description, category) values('MUS','Mauritius','UM');
insert into countries(code, description, category) values('MEX','Mexico','UM');
insert into countries(code, description, category) values('FSM','Micronesia, Fed. Sts.','LM');
insert into countries(code, description, category) values('MDA','Moldova','LM');
insert into countries(code, description, category) values('MCO','Monaco','H');
insert into countries(code, description, category) values('MNG','Mongolia','LM');
insert into countries(code, description, category) values('MNE','Montenegro','UM');
insert into countries(code, description, category) values('MAR','Morocco','LM');
insert into countries(code, description, category) values('MOZ','Mozambique','L');
insert into countries(code, description, category) values('MMR','Myanmar','LM');
insert into countries(code, description, category) values('NAM','Namibia','UM');
insert into countries(code, description, category) values('NRU','Nauru','UM');
insert into countries(code, description, category) values('NPL','Nepal','L');
insert into countries(code, description, category) values('NLD','Netherlands','H');
insert into countries(code, description, category) values('NCL','New Caledonia','H');
insert into countries(code, description, category) values('NZL','New Zealand','H');
insert into countries(code, description, category) values('NIC','Nicaragua','LM');
insert into countries(code, description, category) values('NER','Niger','L');
insert into countries(code, description, category) values('NGA','Nigeria','LM');
insert into countries(code, description, category) values('MKD','North Macedonia','UM');
insert into countries(code, description, category) values('MNP','Northern Mariana Islands','H');
insert into countries(code, description, category) values('NOR','Norway','H');
insert into countries(code, description, category) values('OMN','Oman','H');
insert into countries(code, description, category) values('PAK','Pakistan','LM');
insert into countries(code, description, category) values('PLW','Palau','H');
insert into countries(code, description, category) values('PAN','Panama','H');
insert into countries(code, description, category) values('PNG','Papua New Guinea','LM');
insert into countries(code, description, category) values('PRY','Paraguay','UM');
insert into countries(code, description, category) values('PER','Peru','UM');
insert into countries(code, description, category) values('PHL','Philippines','LM');
insert into countries(code, description, category) values('POL','Poland','H');
insert into countries(code, description, category) values('PRT','Portugal','H');
insert into countries(code, description, category) values('PRI','Puerto Rico','H');
insert into countries(code, description, category) values('QAT','Qatar','H');
insert into countries(code, description, category) values('ROU','Romania','UM');
insert into countries(code, description, category) values('RUS','Russian Federation','UM');
insert into countries(code, description, category) values('RWA','Rwanda','L');
insert into countries(code, description, category) values('WSM','Samoa','UM');
insert into countries(code, description, category) values('SMR','San Marino','H');
insert into countries(code, description, category) values('STP','São Tomé and Principe','LM');
insert into countries(code, description, category) values('SAU','Saudi Arabia','H');
insert into countries(code, description, category) values('SEN','Senegal','LM');
insert into countries(code, description, category) values('SRB','Serbia','UM');
insert into countries(code, description, category) values('SYC','Seychelles','H');
insert into countries(code, description, category) values('SLE','Sierra Leone','L');
insert into countries(code, description, category) values('SGP','Singapore','H');
insert into countries(code, description, category) values('SXM','Sint Maarten (Dutch part)','H');
insert into countries(code, description, category) values('SVK','Slovak Republic','H');
insert into countries(code, description, category) values('SVN','Slovenia','H');
insert into countries(code, description, category) values('SLB','Solomon Islands','LM');
insert into countries(code, description, category) values('SOM','Somalia','L');
insert into countries(code, description, category) values('ZAF','South Africa','UM');
insert into countries(code, description, category) values('SSD','South Sudan','L');
insert into countries(code, description, category) values('ESP','Spain','H');
insert into countries(code, description, category) values('LKA','Sri Lanka','UM');
insert into countries(code, description, category) values('KNA','St. Kitts and Nevis','H');
insert into countries(code, description, category) values('LCA','St. Lucia','UM');
insert into countries(code, description, category) values('MAF','St. Martin (French part)','H');
insert into countries(code, description, category) values('VCT','St. Vincent and the Grenadines','UM');
insert into countries(code, description, category) values('SDN','Sudan','LM');
insert into countries(code, description, category) values('SUR','Suriname','UM');
insert into countries(code, description, category) values('SWE','Sweden','H');
insert into countries(code, description, category) values('CHE','Switzerland','H');
insert into countries(code, description, category) values('SYR','Syrian Arab Republic','L');
insert into countries(code, description, category) values('TWN','Taiwan, China','H');
insert into countries(code, description, category) values('TJK','Tajikistan','L');
insert into countries(code, description, category) values('TZA','Tanzania','L');
insert into countries(code, description, category) values('THA','Thailand','UM');
insert into countries(code, description, category) values('TLS','Timor-Leste','LM');
insert into countries(code, description, category) values('TGO','Togo','L');
insert into countries(code, description, category) values('TON','Tonga','UM');
insert into countries(code, description, category) values('TTO','Trinidad and Tobago','H');
insert into countries(code, description, category) values('TUN','Tunisia','LM');
insert into countries(code, description, category) values('TUR','Turkey','UM');
insert into countries(code, description, category) values('TKM','Turkmenistan','UM');
insert into countries(code, description, category) values('TCA','Turks and Caicos Islands','H');
insert into countries(code, description, category) values('TUV','Tuvalu','UM');
insert into countries(code, description, category) values('UGA','Uganda','L');
insert into countries(code, description, category) values('UKR','Ukraine','LM');
insert into countries(code, description, category) values('ARE','United Arab Emirates','H');
insert into countries(code, description, category) values('GBR','United Kingdom','H');
insert into countries(code, description, category) values('USA','United States','H');
insert into countries(code, description, category) values('URY','Uruguay','H');
insert into countries(code, description, category) values('UZB','Uzbekistan','LM');
insert into countries(code, description, category) values('VUT','Vanuatu','LM');
insert into countries(code, description, category) values('VEN','Venezuela, RB','UM');
insert into countries(code, description, category) values('VNM','Vietnam','LM');
insert into countries(code, description, category) values('VIR','Virgin Islands (U.S.)','H');
insert into countries(code, description, category) values('PSE','West Bank and Gaza','LM');
insert into countries(code, description, category) values('YEM','Yemen, Rep.','L');
insert into countries(code, description, category) values('ZMB','Zambia','LM');
insert into countries(code, description, category) values('ZWE','Zimbabwe','LM');
