INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (1,'Initiating Devices',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (2,'Polymerization Ion Exchangers',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (3,'Car Tires',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (4,'Transmission Belts',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (5,'Miscellaneous Rubber',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (6,'Casks and Barrels',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (7,'Coated Paper',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (8,'Bonded Fiber Fabrics',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (9,'Textiles Fabrics for Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (10,'Polishing Stones',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (11,'Abrasive Powder',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (12,'Unworked Cast Glass',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (13,'Safety Glass',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (14,'Iron Wire',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (15,'Metal Railway Material',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (16,'Iron Pipes',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (17,'Seamless Iron Tubes',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (18,'Iron Tubes',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (19,'Iron and Steel Forging',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (20,'Worked Nickel',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (21,'Fasteners',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (22,'Interchangeable Tool Parts',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (23,'Miscellaneous Indoors Sanitary Ware of Base Metal',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (24,'Locksmith Hardware',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (25,'Metal Chains',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (26,'Metal Springs',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (27,'Steam Power Units',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (28,'Miscellaneous Parts of Steam Power Units',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (29,'Motor Vehicles Piston Engines',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (30,'Internal Combustion Engines for Boats',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (31,'Miscellaneous Combustion Engines',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (32,'Piston Engine Parts',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (33,'DC Motors',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (34,'Electric Motors and AC Generators',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (35,'Rotary Converters',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (36,'Miscellaneous Rotating Electric Plant Parts',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (37,'Nuclear Reactors',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (38,'Miscellaneous Engines',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (39,'Soil Preparation Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (40,'Harvesting Machines',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (41,'Dairy Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (42,'Miscellaneous Agricultural Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (43,'Track Laying Tractors',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (44,'Tractors',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (45,'Road Rollers',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (46,'Construction Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (47,'Miscellaneous Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (48,'Sewing Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (49,'Textile Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (50,'Yarn Preparing Machines',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (51,'Auxiliary Weaving Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (52,'Miscellaneous Textile Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (53,'Cellulose Pulp Making Machines',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (54,'Paper Making Machines',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (55,'Paper Making Machine Parts',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (56,'Type Setting Machines',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (57,'Printing Presses',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (58,'Miscellaneous Printing Machines',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (59,'Bookbinding Machines',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (60,'Printing Machine Parts',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (61,'Grain Milling Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (62,'Miscellaneous Food-Processing Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (63,'Machine Tools for Specialized Industries',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (64,'Miscellaneous Mineral Working Tools',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (65,'Machinery for Specialized Industries',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (66,'Metal Cutting Machines',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (67,'Metal Forming Machine Tool',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (68,'Miscellaneous Metalworking Machine-Tools',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (69,'Tool Holders',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (70,'Parts of Metalworking Machine Tools',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (71,'Miscellaneous Metallurgy Equipment',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (72,'Rolling Mills',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (73,'Miscellaneous Metalworking Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (74,'Gas Generators',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (75,'Furnaces',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (76,'Industrial Furnaces and Ovens',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (77,'Miscellaneous Heating and Cooling Equipment',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (78,'Centrifugal Pumps',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (79,'Rotary Pumps',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (80,'Miscellaneous Pumps',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (81,'Miscellaneous Liquid Pump Parts',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (82,'Air Pumps and Compressors',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (83,'Miscellaneous Pump Parts',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (84,'Fans and Blowers',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (85,'Centrifuges',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (86,'Filtering and Purifying Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (87,'Miscellaneous Centrifuge and Filtering Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (88,'Factory Trucks',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (89,'Lifting and Loading Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (90,'Miscellaneous Parts of Lifting Machinery',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (91,'Pneumatic Power Hand Tools',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (92,'Miscellaneous Non-Electrical Machines',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (93,'Roller Bearings',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (94,'Valves',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (95,'Pulley System Parts',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (96,'Miscellaneous Non-Electrical Machinery Parts',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (97,'Circuit Breakers and Panels',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (98,'Electrical Insulators',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (99,'Electric Heating Devices',1,FLOOR(RAND()*(1000-100+1)+100),1);
INSERT INTO [dbo].[Products]([id],[Description], [UserId], Price, ProductTypeId) values (100,'Automotive Electrical Equipment',1,FLOOR(RAND()*(1000-100+1)+100),1);
